### ISSUE TITLE
Cryptodome Cipher (even after uninstalling/reinstalling requirements.txt)

### ISSUE THREAD

**Issue by ae22** [favll/pogom#191] opened 2016-08-10 03:48 UTC
## Checklist
 - [ ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ ] I have checked if this issue already exists (both open and closed issues)
 - [ ] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [ ] I'm using a descriptive title for this issue

## My Issue

...Traceback (most recent call last):
  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "C:\pogom8916\pogom-master\pogom\app.py", line 18, in <module>
    from .scan import ScanMetrics, Scanner
  File "C:\pogom8916\pogom-master\pogom\scan.py", line 16, in <module>
    from pgoapi import PGoApi
  File "C:\pogom8916\pogom-master\pogom\pgoapi\__init__.py", line 51, in <module                                                                                                    >
    from .pgoapi import PGoApi
  File "C:\pogom8916\pogom-master\pogom\pgoapi\pgoapi.py", line 40, in <module>
    from .auth_google import AuthGoogle
  File "C:\pogom8916\pogom-master\pogom\pgoapi\auth_google.py", line 33, in <mod                                                                                                    ule>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 79, in                                                                                                     <module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 73, in <modu                                                                                                    le>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\lib\site-packages\Cryptodome\IO\_PBES.py", line 44, in <modu                                                                                                    le>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\__init__.py", line 78, i                                                                                                    n <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\_mode_ecb.py", line 46,                                                                                                     in <module>
    """
  File "C:\Python27\lib\site-packages\Cryptodome\Util\_raw_api.py", line 168, in                                                                                                     load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'

Please note that I tried uninstalling and reinstalling the requirements, as it said to do. I am still getting the same error.

**Comment by nborrmann** [comment] 2016-08-10 09:23
Dupe of #130

**Closed by nborrmann** 2016-08-10 09:23 UTC
