### ISSUE TITLE
I got this Error, please help me

### ISSUE THREAD

**Issue by rzkingaioria** [favll/pogom#131] opened 2016-08-09 03:02 UTC
http://prnt.sc/c3ciyy

**Comment by niayh** [comment] 2016-08-09 03:10
I encountered this earlier with accounts I had just created. I saw a previous post from one of the devs claiming that they do a ToS check and accept if necessary; however, when I signed into one of the accounts I was using, the ToS popped up. That said, I'm not entirely sure the ToS check is functioning in this project at the moment

**Comment by favll** [comment] 2016-08-09 08:01
Duplicate of #123

**Closed by favll** 2016-08-09 08:01 UTC
