### ISSUE TITLE
Rate-limit

### ISSUE THREAD

**Issue by warshooter** [favll/pogom#169] opened 2016-08-09 18:48 UTC
Getting the following warning constantly:

2016-08-09 20:40:04,242 [       scan] [   INFO] Completed 63.43% of scan.
2016-08-09 20:40:04,515 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?

Any idea.

Edit: I was on a VPN. Appears to be te issue. I still get the warnings sometimes.

**Comment by djv2** [comment] 2016-08-09 19:02
there is a whole other discussion on this - https://github.com/favll/pogom/issues/152

to sum it up, you probably have been banned - either IP ban or account softban

**Comment by nborrmann** [comment] 2016-08-09 19:13
Dupe of #152

**Closed by nborrmann** 2016-08-09 19:13 UTC
