### ISSUE TITLE
Unable to see anything on the map

### ISSUE THREAD

**Issue by samsbase** [favll/pogom#24] opened 2016-07-27 01:16 UTC
Here is my javascript console as promised

http://puu.sh/qfHQi/67b80d027d.png

**Comment by nborrmann** [comment] 2016-07-27 01:19
Ok, I see. The problem is with the ES6 template strings in line 100-137 of maps.js.

I'll fix it tomorrow (if nobody sent a pr until then).

**Comment by samsbase** [comment] 2016-07-27 01:25
brilliant thanks

**Comment by nborrmann** [comment] 2016-07-27 09:08
Should be fixed in ea72e2c24e1b5c53cacf37a7aeb68087eb9b0583. Please comment if it still doesn't work. Closing this for now.

**Closed by nborrmann** 2016-07-27 09:08 UTC
Labels: bug, in progress
