### ISSUE TITLE
Large portion of scanned area barren when there should be many pokemon.

### ISSUE THREAD

**Issue by DanHazard** [favll/pogom#55] opened 2016-07-28 12:57 UTC
![pogomap](https://cloud.githubusercontent.com/assets/11038145/17212958/9f04f8da-5497-11e6-945f-19a17832f0cb.png)

Login: google
Scan area: 10000
Scan Started: ~8pm CST
Scan issues: Sometime between ~11pm CST and 6:20am CST
Other: -c not in use

So this is what my map looked like when I woke up this morning.  The Scan was still running, but for some reason only populating areas on the outer rim of the area.  **There were no error messages**.

Previously the scan was not populating any pokemon in this area, but rather only pokemon in the empty space.  The scan had been set to 10000, so I assumed it was simply too large a radius for the algorithm to handle.

I tried moving the point around, but it only populated pokemon in areas that were previously part of the outer rim of the initial search.

I resolved the issue by swapping to my PTC account and restarting the scan.  I had some different issues then so I won't post them here, but it did populate the previously barren area though I don't know how accurate it was.

**Comment by naisho** [comment] 2016-07-28 14:58
pokemon typically despawn in 15 minutes, so this looks like intended behavior.  your scan area is so high that its still not finished on the first pass and the pokemon in the middle have despawned already.

**Comment by DanHazard** [comment] 2016-07-28 15:33
You would assume so, but I was personally monitoring it from 8pm until 10pm and this did not happen, the middle area remained populated and repopulated constantly, while the outer area was not.  The scans were completing in maybe 3 minutes?  I wasn't timing it, but it sure wasn't more than 15 minutes to scan the 10000 radius.

**Comment by favll** [comment] 2016-07-28 22:27
Can you give me the location you have set as the scan center so I can take a look at this?

**Comment by DanHazard** [comment] 2016-07-29 01:39
Here is the command I was using to run said scan:

python runserver.py -a google -u username -p password -l 41.880553298809645,-87.64866828918457 -r 10000

**Comment by favll** [comment] 2016-08-08 07:35
Please check if this is happening in the new version as well. Closing this for now.

**Closed by favll** 2016-08-08 07:35 UTC
Labels: bug
