### ISSUE TITLE
Pokemon disappears in 594 hours

### ISSUE THREAD

**Issue by diputz42** [favll/pogom#262] opened 2016-08-12 20:16 UTC
I'm scanning my city and a handful of pokemon appear now and then as disappearing in 594 hours and change. Looked into the DB, and for whatever reason, some pokemon are logged in the DB as disappearing at 2016-09-06 14:56:22.52700. I tried manually deleting the DB entries, but more pop up throughout the scan.

**Comment by TilkIG** [comment] 2016-08-12 20:22
See #260

**Comment by compuguy** [comment] 2016-08-12 21:42
This is a dupe of #260 which a fix is in testing (thanks seikur0!)

**Closed** 2016-08-13 15:23 UTC
