### ISSUE TITLE
3 Error messages, Empty responses, Map download failed, and status 3.

### ISSUE THREAD

**Issue by Devasten** [favll/pogom#291] opened 2016-08-14 22:50 UTC
## Checklist
 - [x ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x ] I have checked if this issue already exists (both open and closed issues)
 - [x ] I am using the most recent version of pogom from the master branch
 - [x ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [x ] I'm posting the complete log
 - [x ] I'm using a descriptive title for this issue

## My Issue
I'm getting a "Received valid response but with
out any data. Possibly rate-limited?" every time the scan updates the percentage value in the command line, and then every so often im also getting a status 3, and then every 30-45 seconds im getting a "Map download failed" Any Ideas? Using a VPN and have tried changing my IP.
Running 22 accounts, have not tampered with scan.py at all, issue started lastnight.(https://github.com/favll/pogom/files/417315/New.Text.Document.4.txt)

**Comment by Mickey32111** [comment] 2016-08-14 23:12
You have some banned accounts active. Update by preforming a git pull, then remove the accounts that throw up the Status 3 Error

**Comment by Mickey32111** [comment] 2016-08-14 23:13
Dupe of #283

**Comment by Devasten** [comment] 2016-08-15 00:39
Already did a git pull, removed the accounts, it's no longer giving me accounts to remove, yet status 3 still pops up

**Comment by Mickey32111** [comment] 2016-08-15 01:41
I get Status 3's when adding new brand new accounts, but they stop after a restart.

**Comment by nborrmann** [comment] 2016-08-15 06:57
Dupe

**Closed by nborrmann** 2016-08-15 06:57 UTC

**Comment by labaland** [comment] 2016-08-15 20:39
How do you use vpn with pogo map?! can u acsses your site from another network when its up ?
