### ISSUE TITLE
Login loop after a couple hours of use

### ISSUE THREAD

**Issue by iMagooo** [favll/pogom#205] opened 2016-08-10 14:23 UTC
## Checklist
 - [X] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [X] I have checked if this issue already exists (both open and closed issues)
 - [X] I am using the most recent version of pogom from the master branch
 - [X] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [X] I'm posting the complete log
 - [X] I'm using a descriptive title for this issue

## My Issue

Begins to infinitely loop after a couple hours of use. Always 3 accounts involved in the loop, I'm going to go out on a limb and say that this number correlates with the number of threads (also 3). No debug log as yet. Running on Rasbian, current source from master, 56 accounts being used.

![login](https://cloud.githubusercontent.com/assets/4627905/17557202/6ec77ada-5f55-11e6-837d-997434a3a51b.png)

Apologies for the rushed name scrubbing, you should get the idea.

**Comment by pixmaip** [comment] 2016-08-10 14:40
I confirm, same thing on Ubuntu server 15.04 x64. This loop actually made the map crash after a while.

**Comment by Gabboplano** [comment] 2016-08-10 14:41
I confirm this on Windows 10

**Comment by Baklap4** [comment] 2016-08-10 14:43
Confirmed Debian x64

**Comment by mandino63** [comment] 2016-08-10 14:44
Confirmed Centos 7 x64, mine got into a login loop for 4 accs till my server got softbanned.

**Comment by omlet05** [comment] 2016-08-10 16:00
Same in docker ;)

**Comment by Lionir** [comment] 2016-08-10 16:15
Confirmed Win7 x64

**Comment by fedemene** [comment] 2016-08-10 18:46
Same on raspberry pi (debian).

**Comment by Odeskin** [comment] 2016-08-10 22:27
Confirmed - Win10 x64

**Comment by Subodai** [comment] 2016-08-10 22:34
Confirmed - Win10 x64, 10 accounts 3 threads. Goes into an endless loop of expiring logins

**Comment by ShadyBS** [comment] 2016-08-11 00:06
Niantic is fucking us :(

**Comment by iMagooo** [comment] 2016-08-11 00:20
@ShadyBS do you have logs to support your statement or is it purely conjecture?

**Comment by snicker** [comment] 2016-08-11 00:24
I have other scanners running and have not been softbanned since I stopped running pogom. This issue is causing the softbans. The logins are hammering the server and they are automatically timebanning IP addresses.

**Comment by iMagooo** [comment] 2016-08-11 00:29
Typically restarting the python script has fixed the problem straight away, and has a few times now. Unless the restart has been perfectly timed, I'm not convinced it's an IP ban. Account soft ban? Maybe.

**Comment by iMagooo** [comment] 2016-08-11 00:54
Although, as far as I'm aware, soft bans only stop Pokémon from showing up. This wouldn't explain the problems logging into an account.

**Comment by midoritest** [comment] 2016-08-11 06:02
I have the same problem. I logged the remaining time and it seems like auth_provider._ticket_expire is in the past.

![image](https://cloud.githubusercontent.com/assets/20552982/17579880/f2ed64ac-5f99-11e6-86d3-1a549d7ae02f.png)

**Comment by dikkedeur** [comment] 2016-08-11 07:51
got the same, it goes in an endless loop.
closed the scanner and started up just to see they are all softbanned due that.
possibly its due massive ( 40 accounts ) trying to login at the same time.
best way would be that we add a sleep timer for login accounts, so that we dont try to login with 40 accounts or even more at the same time.
so when you start the server it logs in with 1 account, few seconds later the second etc.etc.
it will take some time before all 40 accounts are logged in due that, but it will avoid that the server is bumping the accounts right away propably...

**Comment by midoritest** [comment] 2016-08-11 08:33
Another log. It seems like the _ticket_expire is already divided by 1000 so when it divides again before subtracting the current timestamp, I get a negative remaining time, which is smaller than 60 so it tries to log in again.

![image](https://cloud.githubusercontent.com/assets/20552982/17582996/0a31a834-5faf-11e6-9fcd-bd61d9242647.png)

**Comment by stekern** [comment] 2016-08-11 09:41
I have encountered the same problem on OS X with 160 accounts, 7 threads.

I wonder if it can be temporarily fixed by adding a simple check for negative numbers on line 301 in pogom/pgoapi/pgoapi.py.

Something like this
`if remaining_time < 60 and remaining_time >= 0:`

**Comment by midoritest** [comment] 2016-08-11 09:47
> I wonder if it can be temporarily fixed by adding a simple check for negative numbers on line 301 in pogom/pgoapi/pgoapi.py.

I thinks it's normal to have values like a few seconds negative depending the call rate but not -1470000000..

**Comment by nborrmann** [comment] 2016-08-11 09:49
Thanks for the log! It's helping us locate the bug. Though we don't have fix ready yet.

The issue lies deeper than the negative timestamps (we're using negative time diffs to force a re-login sometimes, the problem is what's causing that reset).

**Comment by nborrmann** [comment] 2016-08-11 10:28
I have inserted some log statements into the code on this branch:

https://github.com/favll/pogom/tree/log-login-process

Please check it out and post your logs when the bug occurs.

**Comment by omlet05** [comment] 2016-08-11 10:59
hi, 

here is the common output:

> 2016-08-11 10:57:27,548 [     pgoapi] [   INFO] Login successful: l09qXWwfkr6glLL
> 2016-08-11 10:57:27,548 [    rpc_api] [WARNING] No Session Ticket found - using OAUTH Access Token
> 2016-08-11 10:57:27,567 [   auth_ptc] [WARNING] access_token=TGT-13024835-NvVlT3Bno5BO3DwkOsMBez6zOUkTxprlHB6UaXWvrvAXZWJQzN-sso.pokemon.com&expires=10800 200 https://sso.pokemon.com/sso/oauth2.0/accessToken

**Comment by Clavus** [comment] 2016-08-11 14:52
Happens here too, Windows 10. Goes into a loop of attempting login, login expires, etc. With just 6 accounts. Restarting the server fixes it for a while.

**Comment by midoritest** [comment] 2016-08-11 15:03
Another log with the logging branch.

https://gist.github.com/midoritest/c7292257f4968d4e3591f3f6ff6ad11a

**Comment by nborrmann** [comment] 2016-08-11 15:26
We need a log of when the error occurs.

**Comment by kiralydavid** [comment] 2016-08-11 15:31
The log in my comment above is from the time when the error happened. After that accs 208, 209, 214 looped over and over.

**Comment by midoritest** [comment] 2016-08-11 15:31
The log in my comment above is from the time when the error happened. After that accs 208, 209, 214 looped over and over.

**Comment by nborrmann** [comment] 2016-08-11 16:24
We found the bug. It's really stupid. The server announces an expiry time of 3 hours for the access token, but the actual expiry time is 2 hours. Fix coming soon.

**Comment by omlet05** [comment] 2016-08-11 16:55
Do you think that the account are ban?

**Comment by mrfantomex** [comment] 2016-08-11 19:00
Sounds like you've figured it out, but for what its worth I seem to notice this coincides with the exact moment I get a soft-ip-ban.

**Comment by favll** [comment] 2016-08-12 07:32
Fixed in fd879e92e29da3cf38c1ebc093913512ef68dce0
Further improved in 1436d13d228b0cec81c26be456b7185d53971a50

**Closed by favll** 2016-08-12 07:32 UTC
Labels: bug, in progress
