### ISSUE TITLE
Some warnings in cmd - don't know why

### ISSUE THREAD

**Issue by acmt** [favll/pogom#212] opened 2016-08-10 18:58 UTC
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ ] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [ ] I'm using a descriptive title for this issue

## My Issue

I have some warning and i don't know why, and what i doing wrong

I'm using a descriptive title for this issue

maybe everything is ok, but i don't have enough knowledge to judge this
![pogom](https://cloud.githubusercontent.com/assets/1223951/17566187/b1ace54e-5f3a-11e6-9f40-f3fcc0a78060.JPG)

My OS: Windows 8.1
Python: 2.7.12
Pip: 8.1.2

**Comment by nborrmann** [comment] 2016-08-10 19:04
Dupe of #152

**Closed by nborrmann** 2016-08-10 19:04 UTC
