### ISSUE TITLE
Is this patched now?

### ISSUE THREAD

**Issue by obie7712** [favll/pogom#61] opened 2016-07-29 02:36 UTC
This was easily the best live map but its suddenly stopped working a few hours ago.
Is this the end? or is there any workaround

**Comment by favll** [comment] 2016-07-29 02:49
Due to the throtteling the -c option does not work at the moment. We have released a hotfix so that you can use the map without the -c option. However, it will not be as fast as before. We are currently evaluating options to achieve higher scan speeds again. Also duplicate of #58

**Closed by favll** 2016-07-29 02:49 UTC
