### ISSUE TITLE
Received valide response

### ISSUE THREAD

**Issue by EiTeR94** [favll/pogom#201] opened 2016-08-10 11:45 UTC
Hi since few hours now, i get this error, and no more pokemon are showed on the map.

![capture](https://cloud.githubusercontent.com/assets/20646280/17552528/b9126a46-5f00-11e6-8f94-375c65e4480c.PNG)

any idea?

**Comment by Baklap4** [comment] 2016-08-10 11:47
Duplicate of #152

**Closed** 2016-08-10 12:25 UTC
