### ISSUE TITLE
REQUEST: Add ability to edit & move locations.

### ISSUE THREAD

**Issue by gideonfisk** [favll/pogom#322] opened 2016-08-17 23:37 UTC
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue
It's a painfully slow process trying to get a number of adjacent locations arranged so that they have optimal size and overlap for the coverage one desires. One must either hand-edit the config.json or painstakingly delete and recreate the locations.

If we could simply drag locations to re-arrange them and have the ability to edit the radius this would make the entire process much easier and far more natural.
...

**Comment by favll** [comment] 2016-08-18 00:19
Duplicate of #159

**Closed by favll** 2016-08-18 00:19 UTC
