### ISSUE TITLE
Pokemon stopped showing

### ISSUE THREAD

**Issue by 001nathan100** [favll/pogom#200] opened 2016-08-10 11:34 UTC
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [x] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue
Everything worked fine for two days, running the map with 14 accounts. Now just when I woke up the map stopped working and gave me the following error: http://i.imgur.com/1G34qJd.png

I changed nothing config wise.
...

**Comment by 001nathan100** [comment] 2016-08-10 11:37
UPDATE: my app seems to be showing as well, no pokestops no gyms, nothing.

**Comment by Baklap4** [comment] 2016-08-10 11:45
Duplicate of #152

**Closed** 2016-08-10 12:11 UTC
