### ISSUE TITLE
No Pokemon displayed

### ISSUE THREAD

**Issue by Arepas** [favll/pogom#136] opened 2016-08-09 04:53 UTC
Hi I was running the scan in first time with a single account, but running very slow...0.01...0.3....0.4.... I tried with 2 accounts and its going faster but I cant see any pokemon after scan reach 100%.  Scan radios betweem 100-1000 and still nothing

Any advise? example at 200radio
![none](https://cloud.githubusercontent.com/assets/20797937/17504968/6b30b264-5db2-11e6-83f1-604fa1591e2e.png)

**Comment by Gabboplano** [comment] 2016-08-09 05:42
...add accounts?

**Comment by favll** [comment] 2016-08-09 08:05
Is your scan restarting after this or is it stuck at 100%? It is very much possible that there are no Pokémons in a radius this small.

**Comment by nborrmann** [comment] 2016-08-09 11:14
Check the js console for errors

**Comment by LoebegPip** [comment] 2016-08-09 12:33
Got the exact same issue. No js errors in console log.
My accounts (2) keep looping from 0 to 100%.
My map which has 1 location with a radius of 500m stays empty.
It's in the middle of a medium sized city so there should actually be a bunch of stuff.

**Comment by nborrmann** [comment] 2016-08-09 12:35
Dupe of #152

**Closed by nborrmann** 2016-08-09 12:35 UTC
