### ISSUE TITLE
[Feature Request] Remove one instance of a Pokemon from the map

### ISSUE THREAD

**Issue by Chris221** [favll/pogom#243] opened 2016-08-11 23:12 UTC
Checklist
 - [X] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [X] I have checked if this issue already exists (both open and closed issues)
 - [X] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [X] I'm using a descriptive title for this issue

## My Issue

It would be really nice if the ability to remove one instance of say an _Eevee_, or any other Pokemon, from the map after you have caught it, failed to catch it, or just want it off your map for an other personal reason.

...

**Comment by VergaraF** [comment] 2016-08-12 00:59
Maybe you can mark it as "caught" and remove the marker from the map... I highly doubt this can be done automatically from code as the scanner doesn't interact directly with your account (and you wish not to, you'd get ban in no time).

**Comment by Chris221** [comment] 2016-08-12 01:09
Yes that's what mean just like notify it would have a caught or remove option too

**Comment by favll** [comment] 2016-08-12 07:41
Duplicate of #238

**Closed by favll** 2016-08-12 07:41 UTC
