### ISSUE TITLE
KeyError: 'GET_MAP_OBJECTS'

### ISSUE THREAD

**Issue by DanHazard** [favll/pogom#60] opened 2016-07-29 01:44 UTC
KeyError: 'GET_MAP_OBJECTS'
2016-07-28 20:42:19,790 [     search] [   INFO] Completed  0.73% of scan.
2016-07-28 20:42:19,815 [     search] [  ERROR] Failed to parse response: {'responses': {}}
Traceback (most recent call last):
  File "c:\Pokemonstuff\pogom\pogom\search.py", line 129, in search
    parse_map(response_dict)
  File "c:\Pokemonstuff\pogom\pogom\models.py", line 110, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']

Not really sure what's up with this, could my API be FUBAR?

**Comment by favll** [comment] 2016-07-29 02:50
Due to the throtteling the -c option does not work at the moment. We have released a hotfix so that you can use the map without the -c option. However, it will not be as fast as before. We are currently evaluating options to achieve higher scan speeds again. Also, duplicate of #60

**Closed by favll** 2016-07-29 02:50 UTC
